### ISSUE TITLE
java2nb

### ISSUE THREAD

**Issue by noryar1** [201206030/fiction_house#1]
<dependency>
            <groupId>com.java2nb</groupId>
            <artifactId>java2nb</artifactId>
            <version>1.0.0-release</version>
        </dependency>
这个SDK包没有公开啊？

**Comment by 201206030** [comment]
还在完善中，完善后开源，暂时用我的maven私服，qq群里领取。

**Comment by 201206030** [comment]
java2nbSDK现已集成到项目中，直接拉取最新代码即可。
